# /docker-compose.yml

services:

  # Service ที่ 1: Database (PostgreSQL)
  db:
    image: postgres:latest
    container_name: longsorn-db
    volumes:
      - longsorn-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Service ที่ 2: Backend API (api_main)
  # แก้ไขโดยการลบ "services:" ที่ซ้อนออก และให้ api-server อยู่ระดับเดียวกับ db
  api-server:
    container_name: longsorn-api
    build:
      context: ./backend
      dockerfile: ./services/api-server/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/services/api-server:/app
    env_file:
      - .env
    # แก้ไข command ให้รันผ่าน python -m เพื่อความเสถียรของ Path
    command: ["python", "-m", "uvicorn", "src.api.api:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  longsorn-db-data: