# /docker-compose.yml

services:

  # Service ที่ 1: Database (PostgreSQL)
  db:
    image: postgres:latest # ใช้ Image ของ PostgreSQL 
    container_name: longsorn-db
    volumes:
      - longsorn-db-data:/var/lib/postgresql/data # ทำให้ข้อมูลใน DB ไม่หายไปเมื่อ stop container
    environment:
      - POSTGRES_USER=${DB_USER} # ดึงค่าจากไฟล์ .env
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432" # Map port 5432 ใน container ไปยัง port 5433 ที่เครื่องเราเพื่อป้องกันชนกับ PostgreSQL ที่อาจมีในเครื่อง
    restart: unless-stopped

  # Service ที่ 2: Backend API (api_main)
  api:
    container_name: longsorn-api
    build:
      context: ./backend/services/api-server # บอกว่าให้ไปหา Dockerfile ที่โฟลเดอร์นี้
      dockerfile: Dockerfile
    depends_on:
      - db # บอกว่าให้เริ่ม service 'db' ก่อน แล้วค่อยเริ่ม 'api'
    ports:
      - "8000:8000" # Map port 8000 ของ FastAPI
    volumes:
      - ./backend/services/api-server:/app # **สำคัญมาก:** ทำให้เมื่อเราแก้โค้ด .py บนเครื่องเรา มันจะอัปเดตใน container ทันที (Live Reload)
    env_file:
      - .env # บอกให้ service นี้อ่านค่าจากไฟล์ .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # สั่งให้รัน FastAPI ในโหมด development

volumes:
  longsorn-db-data: # ประกาศ volume ที่จะใช้เก็บข้อมูล DB